In [5]:

from sklearn.datasets import load_iris  

In [6]:
iris=load_iris()

In [7]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [11]:
lr_scores=cross_val_score(LogisticRegression(max_iter=1000), iris.data, iris.target)
lr_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [12]:
np.average(lr_scores)
    

np.float64(0.9733333333333334)

In [13]:
dt_scores=cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dt_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [14]:
np.average(dt_scores)

np.float64(0.9666666666666668)

In [20]:
svm_scores=cross_val_score(SVC(), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [21]:
np.average(svm_scores)

np.float64(0.9666666666666666)

In [23]:
rf_scores=cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rf_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [24]:
np.average(rf_scores   )

np.float64(0.96)