In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [23]:
lr=LogisticRegression(max_iter=10000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9666666666666667

In [24]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)


0.9796296296296296

In [25]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)


0.9685185185185186

In [59]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [60]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [62]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)


In [63]:
get_score(LogisticRegression(max_iter=10000),X_train,X_test,y_train,y_test)

0.9165275459098498

In [64]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9649415692821369

In [73]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
score_lr=[]
score_svm=[]
score_rf=[]


In [74]:
for train_index,test_index in folds.split(digits.data,digits.target):
    X_train,X_test=digits.data[train_index],digits.data[test_index]
    y_train,y_test=digits.target[train_index],digits.target[test_index]
    #print(get_score(LogisticRegression(max_iter=10000),X_train,X_test,y_train,y_test))
    score_lr.append(get_score(LogisticRegression(max_iter=1000),X_train,X_test,y_train,y_test))
    score_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))
   

In [75]:
score_lr

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [76]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [77]:
score_rf

[0.9415692821368948, 0.9499165275459098, 0.9215358931552587]

In [79]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [80]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [81]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.91388889, 0.88055556, 0.95264624, 0.9637883 , 0.93314763])